# Generated by Django 4.2.30 on 2026-10-06 22:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('attraction', 'Attraction'), ('restaurant', 'Restaurant'), ('beach', 'Beach'), ('museum', 'Museum'), ('landmark', 'Landmark'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=20),
        ),
    ]
